#include <TTree.h>
#include <TFile.h>


void removeBranchesFromNtuple() {
    // Example of Root macro to copy a subset of a Tree to a new Tree
    // The input file has been generated by the program in $ROOTSYS/test/Event
    // with   Event 1000 1 1 1
    //Author: Rene Brun
    
    
    //Get old file, old tree and set top branch address
    TFile *oldfile = new TFile("wjets.root");
    TTree *oldtree = (TTree*)oldfile->Get("MVATree");
    oldtree->SetBranchStatus("*",1);
    oldtree->SetBranchStatus("isFake1",0);
    oldtree->SetBranchStatus("isFake0",0);
    //  oldtree->SetBranchStatus("mcevt_pdf_scale",0);
    oldtree->SetBranchStatus("SysFakeWeightCorr",0);
    oldtree->SetBranchStatus("SysFakeOtherCorr",0);
    oldtree->SetBranchStatus("SysFakeFlavCorr",0);
    oldtree->SetBranchStatus("SysFakeStatCorr",0);

    
    
    
    
    //Create a new file + a clone of old tree in new file
    TFile *newfile = new TFile("wjets_new.root","recreate");
    TTree *newtree = oldtree->CloneTree();
    
    newtree->Print();
    newfile->Write();
    delete oldfile;
    delete newfile;
}
